------------------------------------------------------------------------------------------------------------
--서비스 등록하기 카테고리 1,3 들고오기
SELECT * FROM MAIN_CATEGORY;

SELECT THIRD_CATEGORY_NO,THIRD_CATEGORY_NAME,MAIN_CATEGORY_NO 
FROM CATEGORY 
JOIN SUB_CATEGORY USING(SUB_CATEGORY_NO)
ORDER BY 1;

---서비스 등록하기 서비스 데이터 삽입
INSERT INTO "SERVICE"
VALUES(SEQ_SERVICE_NO.NEXTVAL,#{},#{},#{},#{},#{},#{},DEFAULT,DEFAULT,#{},#{})

----서비스 테이블에서 데이터 들고 오기 --서비스 연관 첨부파일도 처음 하나만 들고오기(메인사진으로 들고 올거임)
SELECT SERVICE_NO,SERVICE_TITLE,SERVICE_SUMMARY,SERNICE_CONTENT,SERVICE_PRICE,TO_CHAR(SERVICE_PRICE, 'FM999,999,999,999') SERVICE_PRICE_STRING, SERVICE_EDIT_NUM,
SERVICE_WORK_PERIOD,SERVICE_STATUS,SERVICE_CREATE_DATE,THIRD_CATEGORY_NO,FREELANCER_NO,REQUEST_FILE_NO,REQUEST_FILE_PATH
FROM SERVICE
LEFT JOIN (SELECT s.*,
ROW_NUMBER() OVER (PARTITION BY SERVICE_NO ORDER BY REQUEST_FILE_NO) rum
FROM SERVICE_FILE s) USING(SERVICE_NO)
WHERE RUM = 1
AND SERVICE_STATUS NOT IN (5)
AND FREELANCER_NO = 30;

--TO_CHAR(SERVICE_PRICE, 'FM999,999,999,999') 스트링 형식
--1:승인 대기 중, 2:판매 중, 3:미승인, 4:판매 중지,5: 의뢰용일회성서비스
SELECT SERVICE_NO,SERVICE_TITLE,SERVICE_SUMMARY,SERNICE_CONTENT,SERVICE_PRICE,TO_CHAR(SERVICE_PRICE, 'FM999,999,999,999') SERVICE_PRICE_STRING, 
	SERVICE_EDIT_NUM,SERVICE_WORK_PERIOD,
	SERVICE_STATUS,
	CASE WHEN SERVICE_STATUS = 1 THEN '승인대기 중'
	     WHEN SERVICE_STATUS = 2 THEN '판매 중'
	     WHEN SERVICE_STATUS = 3 THEN '미승인'
	     WHEN SERVICE_STATUS = 3 THEN '판매 중지'
	END AS SERVICE_STATUS_STRING
	,SERVICE_CREATE_DATE,THIRD_CATEGORY_NO,FREELANCER_NO,REQUEST_FILE_NO,REQUEST_FILE_PATH
FROM SERVICE
LEFT JOIN (SELECT s.*,
ROW_NUMBER() OVER (PARTITION BY SERVICE_NO ORDER BY REQUEST_FILE_NO) rum
FROM SERVICE_FILE s) USING(SERVICE_NO)
WHERE RUM = 1
AND SERVICE_STATUS NOT IN (5)
AND FREELANCER_NO = 30;





