------------------------------------------------
COMMENT ON COLUMN FMANAGER.GRADE.GRADE_NO IS '등급 번호';--수정
-----------------------------------------------------
COMMENT ON TABLE FMANAGER.BANK IS '은행테이블';
COMMENT ON TABLE FMANAGER.CAREER IS '프리랜서 정보:경력사항 테이블';
COMMENT ON TABLE FMANAGER.CATEGORY IS '세부 카테고리(카테고리3)';
COMMENT ON TABLE FMANAGER.CHAT IS '채팅메세지';
COMMENT ON TABLE FMANAGER.CHAT_ROOM IS '채팅방';
COMMENT ON TABLE FMANAGER.FIELD IS '프리랜서 정보:전문분야';
COMMENT ON TABLE FMANAGER.FREELANCER IS '프리랜서 등록 테이블';
COMMENT ON TABLE FMANAGER.FREELANCER_ACCOUNT IS '프리랜서 계좌';
COMMENT ON TABLE FMANAGER.GRADE IS '프리랜서 등급';
COMMENT ON TABLE FMANAGER.INTEREST IS '회원정보:관심분야 테이블';
COMMENT ON TABLE FMANAGER.LICENSE IS '프리랜서 정보:자격증 테이블';
COMMENT ON TABLE FMANAGER."LIKE" IS '찜한 목록';
COMMENT ON TABLE FMANAGER.MAIN_CATEGORY IS '상위 카테고리(카테고리1)';
COMMENT ON TABLE FMANAGER.MAJOR IS '학력/전공';
COMMENT ON TABLE FMANAGER."MEMBER" IS '회원 테이블';
COMMENT ON TABLE FMANAGER.PORTFOLIO IS '프리랜서정보:포토폴리오';
COMMENT ON TABLE FMANAGER.PROJECT_PROPOSAL IS '프로젝트 제안(프리랜서->의뢰자)';
COMMENT ON TABLE FMANAGER.PROJECT_REQUEST IS '프로젝트 의뢰(의뢰인이 등록)';
COMMENT ON TABLE FMANAGER.REGION IS '프리랜서 정보:지역';
COMMENT ON TABLE FMANAGER.REPORT IS '리뷰 신고 테이블';
COMMENT ON TABLE FMANAGER.REQUEST_FILE IS '의뢰첨부파일';
COMMENT ON TABLE FMANAGER.REVIEW IS '리뷰';
COMMENT ON TABLE FMANAGER.REVIEW_COMMENT IS '리뷰댓글';
COMMENT ON TABLE FMANAGER.SERVICE IS '서비스(프리랜서 등록)';
COMMENT ON TABLE FMANAGER.SERVICE_FILE IS '서비스 첨부파일';
COMMENT ON TABLE FMANAGER.SERVICE_INQUIRY IS '서비스 문의(서비스 상세페이지에서 문의하기)';
COMMENT ON TABLE FMANAGER.SETTLEMENT IS '(관리자페이지)정산 관리 내역';
COMMENT ON TABLE FMANAGER.SUB_CATEGORY IS '부분 카테고리(카테고리2)';
COMMENT ON TABLE FMANAGER.TRADE IS '거래 테이블';
COMMENT ON TABLE FMANAGER.TRADE_REPORT IS '거래 신고';
COMMENT ON TABLE FMANAGER.USER_INQUIRY IS '이용 문의';
COMMENT ON TABLE FMANAGER.USER_INQUIRY_FILE IS '이용문의 첨부파일';
COMMENT ON TABLE FMANAGER."WORK" IS '작업물';

