CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(40)      NOT NULL,
   "MEMBER_PW"   VARCHAR2(30)      NOT NULL,
   "MEMBER_TEL"   CHAR(11)      NOT NULL,
   "MEMBER_NICKNAME"   VARCHAR2(30)      NOT NULL,
   "MEMBER_NAME"   VARCHAR2(20)      NOT NULL,
   "MEMBER_JOB"   VARCHAR2(300)      NOT NULL,
   "AUTHORITY"   NUMBER   DEFAULT 1   NOT NULL
);

ALTER TABLE MEMBER MODIFY MEMBER_PW VARCHAR2(200);
ALTER TABLE MEMBER ADD MEMBER_DELETE_FL CHAR(1) DEFAULT 'N' NOT NULL;
ALTER TABLE MEMBER ADD MEMBER_ENROLL_DATE DATE DEFAULT 'SYSDATE ' NOT NULL;
ALTER TABLE MEMBER ADD FREELANCER_FL CHAR(1) DEFAULT 'N' NOT NULL;

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호 SEQUENCE: SEQ_MEMBER_NO';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일(중복 불가)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 휴대폰(중복 불가)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임(중복 불가)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_JOB" IS '회원 직업';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원 권한(1:회원, 2: 관리자)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ENROLL_DATE" IS '회원 가입일';
COMMENT ON COLUMN "MEMBER"."MEMBER_DELETE_FL" IS '회원 탈퇴 여부 탈퇴:Y 회원:N';
COMMENT ON COLUMN "MEMBER"."FREELANCER_FL" IS '프리랜서 등록 여부 등록:Y 미등록:N';

CREATE TABLE "FREELANCER" (
   "FREELANCER_NO"   NUMBER      NOT NULL,
   "FREELANCER_PERIOD"   NUMBER      NOT NULL,
   "FREE_CONTACT_TIME1"   NUMBER      NOT NULL,
   "FREE_CONTACT_TIME2"   NUMBER      NOT NULL,
   "FREELACER_INTRODUCTION"   VARCHAR2(4000)      NOT NULL,
   "REGION_NO"   NUMBER      NOT NULL,
   "GRADE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "FREELANCER"."FREELANCER_NO" IS '프리랜서 번호(PK+FK(회원번호))';

COMMENT ON COLUMN "FREELANCER"."FREELANCER_PERIOD" IS '프리랜서 기간';

COMMENT ON COLUMN "FREELANCER"."FREE_CONTACT_TIME1" IS '연락가능시간시작';

COMMENT ON COLUMN "FREELANCER"."FREE_CONTACT_TIME2" IS '연락가능시간끝';

COMMENT ON COLUMN "FREELANCER"."FREELACER_INTRODUCTION" IS '프리랜서 자기소개';

COMMENT ON COLUMN "FREELANCER"."REGION_NO" IS '지역 번호(FK)';

COMMENT ON COLUMN "FREELANCER"."GRADE_NO" IS '등급 번호(FK)';

CREATE TABLE "CHAT_ROOM" (
   "CHAT_ROOM_NO"   NUMBER      NOT NULL,
   "CHAT_ROOM_DEL_FL"   CHAR(1)      NOT NULL,
   "CHAT_ROOM_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL,
   "CLIENT_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CHAT_ROOM"."CHAT_ROOM_NO" IS '채팅방 번호 SEQUENCE: SEQ_CHAT_ROOM_NO';

COMMENT ON COLUMN "CHAT_ROOM"."CHAT_ROOM_DEL_FL" IS '채팅방 삭제 여부 Y :삭제 N: 개설';
ALTER TABLE "CHAT_ROOM" MODIFY CHAT_ROOM_DEL_FL DEFAULT 'N';
COMMENT ON COLUMN "CHAT_ROOM"."CHAT_ROOM_CREATE_DATE" IS '채팅방 개설일';

COMMENT ON COLUMN "CHAT_ROOM"."FREELANCER_NO" IS '채팅방 개설자(FREELANCER_NO FK)';

COMMENT ON COLUMN "CHAT_ROOM"."CLIENT_NO" IS '채팅방 참여자(회원번호 FK)';

CREATE TABLE "SERVICE" (
   "SERVICE_NO"   NUMBER      NOT NULL,
   "SERVICE_TITLE"   VARCHAR2(100)      NOT NULL,
   "SERVICE_SUMMARY"   VARCHAR2(1000)      NOT NULL,
   "SERNICE_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "SERVICE_PRICE"   NUMBER      NOT NULL,
   "SERVICE_EDIT_NUM"   NUMBER   DEFAULT 0   NOT NULL,
   "SERVICE_WORK_PERIOD"   NUMBER      NOT NULL,
   "SERVICE_STATUS"   NUMBER   DEFAULT 1   NOT NULL,
   "SERVICE_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "THIRD_CATEGORY_NO"   NUMBER      NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SERVICE"."SERVICE_NO" IS '서비스 번호 SEQUENCE: SEQ_SERVICE_NO';

COMMENT ON COLUMN "SERVICE"."SERVICE_TITLE" IS '서비스 제목';

COMMENT ON COLUMN "SERVICE"."SERVICE_SUMMARY" IS '서비스 한 줄 요약';

COMMENT ON COLUMN "SERVICE"."SERNICE_CONTENT" IS '서비스 내용';

COMMENT ON COLUMN "SERVICE"."SERVICE_PRICE" IS '서비스 가격';

COMMENT ON COLUMN "SERVICE"."SERVICE_EDIT_NUM" IS '서비스 수정 횟수';

COMMENT ON COLUMN "SERVICE"."SERVICE_WORK_PERIOD" IS '서비스 작업 일수';

COMMENT ON COLUMN "SERVICE"."SERVICE_STATUS" IS '1:승인 대기 중, 2:판매 중, 3:미승인, 4:판매 중지,5: 의뢰용일회성서비스';

COMMENT ON COLUMN "SERVICE"."SERVICE_CREATE_DATE" IS '서비스 등록일';

COMMENT ON COLUMN "SERVICE"."THIRD_CATEGORY_NO" IS '카테고리3 번호(FK)';

COMMENT ON COLUMN "SERVICE"."FREELANCER_NO" IS '프리랜서 번호(FK)';

CREATE TABLE "PROJECT_REQUEST" (
   "PROJECT_REQUEST_NO"   NUMBER      NOT NULL,
   "PROJECT_REQUEST_TITLE"   VARCHAR2(200)      NOT NULL,
   "PROJECT_REQUEST_SUMMARY"   VARCHAR2(300)      NOT NULL,
   "PROJECT_REQUEST_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "PROJECT_REQUEST_BUDGET"   NUMBER      NOT NULL,
   "REQUEST_RECRUIT_DATE"   DATE      NOT NULL,
   "REQUEST_WORK_DATE"   DATE      NOT NULL,
   "PROJECT_WORK_PERIOD"   NUMBER      NOT NULL,
   "PROJECT_REQUEST_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "THIRD_CATEGORY_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_REQUEST_NO" IS '프로젝트 의뢰 번호 SEQUENCE: SEQ_PROJECT_REQUEST_NO';

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_REQUEST_TITLE" IS '프로젝트 의뢰 제목';

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_REQUEST_SUMMARY" IS '프로젝트 의뢰 요약';

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_REQUEST_CONTENT" IS '프로젝트 의뢰 사항';

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_REQUEST_BUDGET" IS '프로젝트 의뢰 예산';

COMMENT ON COLUMN "PROJECT_REQUEST"."REQUEST_RECRUIT_DATE" IS '프로젝트 모집 마감일';

COMMENT ON COLUMN "PROJECT_REQUEST"."REQUEST_WORK_DATE" IS '프로젝트 작업 마감일';

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_WORK_PERIOD" IS '프로젝트 작업기간';

COMMENT ON COLUMN "PROJECT_REQUEST"."PROJECT_REQUEST_CREATE_DATE" IS '프로젝트 의뢰 등록일';

COMMENT ON COLUMN "PROJECT_REQUEST"."THIRD_CATEGORY_NO" IS '카테고리3 번호(FK)';

COMMENT ON COLUMN "PROJECT_REQUEST"."MEMBER_NO" IS '회원 번호(FK)';

CREATE TABLE "PROJECT_PROPOSAL" (
   "PROJECT_PROPOSAL_NO"   NUMBER      NOT NULL,
   "PROPOSAL_ADOPT_STATUS"   NUMBER   DEFAULT 1   NOT NULL,
   "PROPOSAL_PRICE"   NUMBER      NOT NULL,
   "PROPOSAL_EDIT_NUM"   NUMBER   DEFAULT 0   NOT NULL,
   "PROPOSAL_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "PROJECT_REQUEST_NO"   NUMBER      NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PROJECT_PROPOSAL"."PROJECT_PROPOSAL_NO" IS '프로젝트 제안 번호 SEQUENCE :SEQ_PROJECT_PROPOSAL_NO';

COMMENT ON COLUMN "PROJECT_PROPOSAL"."PROPOSAL_ADOPT_STATUS" IS '프로젝트 채택 상태 1:대기중 2:채택 3: 모집마감';

COMMENT ON COLUMN "PROJECT_PROPOSAL"."PROPOSAL_PRICE" IS '프로젝트 제안 가격';

COMMENT ON COLUMN "PROJECT_PROPOSAL"."PROPOSAL_EDIT_NUM" IS '프로젝트 수정 횟수';

COMMENT ON COLUMN "PROJECT_PROPOSAL"."PROPOSAL_CREATE_DATE" IS '프로젝트 제안 등록일';

COMMENT ON COLUMN "PROJECT_PROPOSAL"."PROJECT_REQUEST_NO" IS '프로젝트 의뢰 번호(FK:PROJECT_REQUEST)';

COMMENT ON COLUMN "PROJECT_PROPOSAL"."FREELANCER_NO" IS '프리랜서 번호(FK)';

CREATE TABLE "MAIN_CATEGORY" (
   "MAIN_CATEGORY_NO"   NUMBER      NOT NULL,
   "MAIN_CATEGORY_NAME"   VARCHAR2(50)      NOT NULL
);

COMMENT ON COLUMN "MAIN_CATEGORY"."MAIN_CATEGORY_NO" IS '카테고리1 번호';

COMMENT ON COLUMN "MAIN_CATEGORY"."MAIN_CATEGORY_NAME" IS '카테고리1 이름';

CREATE TABLE "SUB_CATEGORY" (
   "SUB_CATEGORY_NO"   NUMBER      NOT NULL,
   "SUB_CATEGORY_NAME"   VARCHAR2(50)      NOT NULL,
   "MAIN_CATEGORY_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SUB_CATEGORY"."SUB_CATEGORY_NO" IS '카테고리2 번호';

COMMENT ON COLUMN "SUB_CATEGORY"."SUB_CATEGORY_NAME" IS '카테고리2 이름';

COMMENT ON COLUMN "SUB_CATEGORY"."MAIN_CATEGORY_NO" IS '카테고리1 번호(FK)';

CREATE TABLE "CATEGORY" (
   "THIRD_CATEGORY_NO"   NUMBER      NOT NULL,
   "THIRD_CATEGORY_NAME"   VARCHAR2(50)      NULL,
   "SUB_CATEGORY_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."THIRD_CATEGORY_NO" IS '카테고리3 번호';

COMMENT ON COLUMN "CATEGORY"."THIRD_CATEGORY_NAME" IS '카테고리 3 이름';

COMMENT ON COLUMN "CATEGORY"."SUB_CATEGORY_NO" IS '카테고리2 번호(FK)';

CREATE TABLE "REVIEW" (
   "REVIEW_NO"   NUMBER      NOT NULL,
   "REVIEW_CONTENT"   VARCHAR2(3000)      NOT NULL,
   "REVIEW_IMAGE"   VARCHAR2(3000)      NOT NULL,
   "REVIEW_STATUS"   NUMBER   DEFAULT 1   NOT NULL,
   "REVIEW_POINT"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS '리뷰 번호 = 거래 번호(PK+FK)';

COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "REVIEW"."REVIEW_IMAGE" IS '리뷰 사진';

COMMENT ON COLUMN "REVIEW"."REVIEW_STATUS" IS '1:게시, 2:신고 중, 3:삭제완료';

COMMENT ON COLUMN "REVIEW"."REVIEW_POINT" IS '리뷰 평점';

CREATE TABLE "SERVICE_INQUIRY" (
   "SERVICE_INQUIRY_NO"   NUMBER      NOT NULL,
   "SERVICE_INQUIRY_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "SERVICE_INQUIRY_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "SERVICE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SERVICE_INQUIRY"."SERVICE_INQUIRY_NO" IS '서비스 문의 번호 SEQUENCE: SEQ_SERVICE_INQUIRY_NO';

COMMENT ON COLUMN "SERVICE_INQUIRY"."SERVICE_INQUIRY_CONTENT" IS '서비스 문의 내용';

COMMENT ON COLUMN "SERVICE_INQUIRY"."SERVICE_INQUIRY_CREATE_DATE" IS '서비스 문의 작성 날짜';

COMMENT ON COLUMN "SERVICE_INQUIRY"."MEMBER_NO" IS '작성 회원 번호(FK)';

COMMENT ON COLUMN "SERVICE_INQUIRY"."SERVICE_NO" IS '서비스 번호(FK)';

CREATE TABLE "USER_INQUIRY" (
   "USER_INQUIRY_NO"   NUMBER      NOT NULL,
   "USER_INQUIRY_TITLE"   VARCHAR2(200)      NOT NULL,
   "USER_INQUIRY_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "USER_INQUIRY_REQUEST"   VARCHAR2(4000)      NULL,
   "USER_INQUIRY_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "USER_INQUIRY"."USER_INQUIRY_NO" IS '이용문의 번호 SEQUENCE: SEQ_USER_INQUIRY_NO';

COMMENT ON COLUMN "USER_INQUIRY"."USER_INQUIRY_TITLE" IS '이용문의 제목';

COMMENT ON COLUMN "USER_INQUIRY"."USER_INQUIRY_CONTENT" IS '이용문의 내용';

COMMENT ON COLUMN "USER_INQUIRY"."USER_INQUIRY_REQUEST" IS '이용문의 답변';

COMMENT ON COLUMN "USER_INQUIRY"."USER_INQUIRY_CREATE_DATE" IS '이용문의 작성 날짜';

COMMENT ON COLUMN "USER_INQUIRY"."MEMBER_NO" IS '회원 번호(FK)';

CREATE TABLE "REPORT" (
   "REPORT_NO"   NUMBER      NOT NULL,
   "REVIEW_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '리뷰 신고 번호 SEQUENCE: SEQ_REPORT_NO';

COMMENT ON COLUMN "REPORT"."REVIEW_NO" IS '리뷰 번호(FK)';

CREATE TABLE "WORK" (
   "WORK_NO"   NUMBER      NOT NULL,
   "WORK_SEND_DATE"   DATE DEFAULT SYSDATE   NOT NULL,
   "TRADE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "WORK"."WORK_NO" IS '작업물 번호 SEQUENCE: SEQ_WORK_NO';

COMMENT ON COLUMN "WORK"."WORK_SEND_DATE" IS '작업물 발송 날짜';

COMMENT ON COLUMN "WORK"."TRADE_NO" IS '거래번호(Fk)';

CREATE TABLE "FIELD" (
   "MAIN_CATEGORY_NO"   NUMBER      NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "FIELD"."MAIN_CATEGORY_NO" IS '카테고리1 번호(PK+FK)';

COMMENT ON COLUMN "FIELD"."FREELANCER_NO" IS '프리랜서 번호(PK+FK)';

CREATE TABLE "CAREER" (
   "CAREER_NO"   NUMBER      NOT NULL,
   "CAREER_FL"   CHAR(1)      NOT NULL,
   "CAREER_COMPANY"   VARCHAR2(300)      NULL,
   "CAREER_DEPARTMENT"   VARCHAR2(300)      NULL,
   "CAREER_POSITION"   VARCHAR2(300)      NULL,
   "CAREER_REGION"   VARCHAR2(300)      NULL,
   "CAREER_PERIOD"   VARCHAR2(20)      NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CAREER"."CAREER_NO" IS '경력사항 번호 SEQUENCE: SEQ_CAREER_NO';

COMMENT ON COLUMN "CAREER"."CAREER_FL" IS 'Y: 경력사항 유, N:경력사항 무';

COMMENT ON COLUMN "CAREER"."CAREER_COMPANY" IS '회사명';

COMMENT ON COLUMN "CAREER"."CAREER_DEPARTMENT" IS '근무부서';

COMMENT ON COLUMN "CAREER"."CAREER_POSITION" IS '직위';

COMMENT ON COLUMN "CAREER"."CAREER_REGION" IS '근무지';

COMMENT ON COLUMN "CAREER"."CAREER_PERIOD" IS '근무기간';

COMMENT ON COLUMN "CAREER"."FREELANCER_NO" IS '프리랜서 번호(FK)';

CREATE TABLE "LICENSE" (
   "LICENSE_NO"   NUMBER      NOT NULL,
   "LICENSE_NAME"   VARCHAR2(1000)      NOT NULL,
   "LICENSE_DATE"   DATE      NOT NULL,
   "LICENSE_AGENCY"   VARCHAR2(1000)      NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "LICENSE"."LICENSE_NO" IS '자격증 번호 SEQUENCE: SEQ_LICENSE_NO';

COMMENT ON COLUMN "LICENSE"."LICENSE_NAME" IS '자격증 이름';

COMMENT ON COLUMN "LICENSE"."LICENSE_DATE" IS '자격증 발급일';

COMMENT ON COLUMN "LICENSE"."LICENSE_AGENCY" IS '자격증 발급 기관';

COMMENT ON COLUMN "LICENSE"."FREELANCER_NO" IS '프리랜서 번호(FK)';

CREATE TABLE "BANK" (
   "BANK_CODE"   NUMBER      NOT NULL,
   "BANK_NAME"   VARCHAR2(20)      NOT NULL
);

COMMENT ON COLUMN "BANK"."BANK_CODE" IS '은행 코드';

COMMENT ON COLUMN "BANK"."BANK_NAME" IS '은행 이름';

CREATE TABLE "PORTFOLIO" (
   "PORTFOLIO_NO"   NUMBER      NOT NULL,
   "PORTFOLIO_TITLE"   VARCHAR2(500)      NOT NULL,
   "PORTFOLIO_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "PORTFOLIO_FILE_PATH"   VARCHAR2(1000)      NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PORTFOLIO"."PORTFOLIO_NO" IS '포트폴리오 번호 SEQUENCE: SEQ_PORTFOLIO_NO';

COMMENT ON COLUMN "PORTFOLIO"."PORTFOLIO_TITLE" IS '포트폴리오 제목';

COMMENT ON COLUMN "PORTFOLIO"."PORTFOLIO_CONTENT" IS '포트폴리오 상세 설명';

COMMENT ON COLUMN "PORTFOLIO"."PORTFOLIO_FILE_PATH" IS '포트폴리오 첨부파일';

COMMENT ON COLUMN "PORTFOLIO"."FREELANCER_NO" IS '프리랜서 번호(FK)';

CREATE TABLE "INTEREST" (
   "MAIN_CATEGORY_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "INTEREST"."MAIN_CATEGORY_NO" IS '카테고리1 번호(PK+FK)';

COMMENT ON COLUMN "INTEREST"."MEMBER_NO" IS '회원 번호(PK+FK)';

CREATE TABLE "REQUEST_FILE" (
   "REQUEST_FILE_NO"   NUMBER      NOT NULL,
   "REQUEST_FILE_PATH"   VARCHAR2(1000)      NOT NULL,
   "REQUEST_FILE_ORDER"   NUMBER      NOT NULL,
   "PROJECT_REQUEST_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REQUEST_FILE"."REQUEST_FILE_NO" IS '의뢰 첨부파일 번호 SEQUENCE: SEQ_REQUEST_FILE_NO';

COMMENT ON COLUMN "REQUEST_FILE"."REQUEST_FILE_PATH" IS '의뢰 첨부파일 경로';

COMMENT ON COLUMN "REQUEST_FILE"."REQUEST_FILE_ORDER" IS '의뢰 첨부파일 순서';

COMMENT ON COLUMN "REQUEST_FILE"."PROJECT_REQUEST_NO" IS '프로젝트 의뢰 번호(FK)';

CREATE TABLE "SERVICE_FILE" (
   "REQUEST_FILE_NO"   NUMBER      NOT NULL,
   "REQUEST_FILE_PATH"   VARCHAR2(1000)      NOT NULL,
   "SERVICE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SERVICE_FILE"."REQUEST_FILE_NO" IS '서비스 첨부파일 번호 SEQUENCE: SEQ_SERVICE_FILE_NO';

COMMENT ON COLUMN "SERVICE_FILE"."REQUEST_FILE_PATH" IS '서비스 첨부파일 경로';

COMMENT ON COLUMN "SERVICE_FILE"."SERVICE_NO" IS '서비스 번호(FK)';

CREATE TABLE "USER_INQUIRY_FILE" (
   "INQUIRY_FILE_NO"   NUMBER      NOT NULL,
   "INQUIRY_FILE_PATH"   VARCHAR2(1000)      NOT NULL,
   "INQUIRY_FILE_ORDER"   NUMBER      NOT NULL,
   "USER_INQUIRY_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "USER_INQUIRY_FILE"."INQUIRY_FILE_NO" IS '이용문의 첨부파일 번호 SEQUENCE: SEQ_INQUIRY_FILE_NO';

COMMENT ON COLUMN "USER_INQUIRY_FILE"."INQUIRY_FILE_PATH" IS '이용문의 첨부파일 경로';

COMMENT ON COLUMN "USER_INQUIRY_FILE"."INQUIRY_FILE_ORDER" IS '이용문의 첨부파일 순서';

COMMENT ON COLUMN "USER_INQUIRY_FILE"."USER_INQUIRY_NO" IS '이용문의 번호(FK)';

CREATE TABLE "TRADE" (
   "TRADE_NO"   NUMBER      NOT NULL,
   "MEMBER_DONE_FL"   NUMBER   DEFAULT 1   NOT NULL,
   "FREELANCER_DONE_FL"   NUMBER   DEFAULT 1   NOT NULL,
   "SERVICE_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "TRADE"."TRADE_NO" IS '거래 번호 SEQUENCE: SEQ_TRADE_NO';

COMMENT ON COLUMN "TRADE"."MEMBER_DONE_FL" IS '1:진행 중, 2: 작업 완료, 3: 주문취소';

COMMENT ON COLUMN "TRADE"."FREELANCER_DONE_FL" IS '1:진행 중, 2: 작업 완료, 3: 주문취소';

COMMENT ON COLUMN "TRADE"."SERVICE_NO" IS '서비스 번호(FK)';

COMMENT ON COLUMN "TRADE"."MEMBER_NO" IS '회원 번호-의뢰인(FK)';

CREATE TABLE "SETTLEMENT" (
   "SETTLEMENT_NO"   NUMBER      NOT NULL,
   "PAYMENT_TYPE"   NUMBER      NOT NULL,
   "USER_NO"   NUMBER      NOT NULL,
   "WORK_STATUS"   NUMBER      NOT NULL,
   "PAYMENT_DATE"   DATE      NOT NULL,
   "PAYMENT_PRICE"   NUMBER      NOT NULL,
   "TRADE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SETTLEMENT"."SETTLEMENT_NO" IS '거래 내역 번호 SEQUENCE: SEQ_SETTLEMENT_NO';

COMMENT ON COLUMN "SETTLEMENT"."PAYMENT_TYPE" IS '거래 종류(1:입금, 2:출금, 3:환불)';

COMMENT ON COLUMN "SETTLEMENT"."USER_NO" IS '거래 회원 번호';

COMMENT ON COLUMN "SETTLEMENT"."WORK_STATUS" IS '1: 진행중, 2: 정산 완료, 3:환불 완료, 4:마감';

COMMENT ON COLUMN "SETTLEMENT"."PAYMENT_DATE" IS '거래 날짜';

COMMENT ON COLUMN "SETTLEMENT"."PAYMENT_PRICE" IS '거래 금액';

COMMENT ON COLUMN "SETTLEMENT"."TRADE_NO" IS '거래 번호(FK)';

CREATE TABLE "REVIEW_COMMENT" (
   "REVIEW_COMMENT_NO"   NUMBER      NOT NULL,
   "REVIEW_COMMENT_CONTENT"   VARCHAR2(3000)      NOT NULL
);

COMMENT ON COLUMN "REVIEW_COMMENT"."REVIEW_COMMENT_NO" IS '리뷰 댓글 번호 = 리뷰 번호(PK+FK)';

COMMENT ON COLUMN "REVIEW_COMMENT"."REVIEW_COMMENT_CONTENT" IS '댓글 내용';

--날짜 추가
CREATE TABLE "TRADE_REPORT" (
   "TRADE_REPORT_NO"   NUMBER      NOT NULL,
   "REPORT_PERSON"   NUMBER      NOT NULL,
   "REPORTED_PERSON"   NUMBER      NOT NULL,
   "TRADE_REPORT_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "REFUND_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "TRADE_REPORT_FILE_PATH"   VARCHAR2(1000)      NULL,
   "TRADE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "TRADE_REPORT"."TRADE_REPORT_NO" IS '거래 신고 번호 SEQUENCE: SEQ_TRADE_REPORT_NO';

COMMENT ON COLUMN "TRADE_REPORT"."REPORT_PERSON" IS '거래 신고자 회원 번호';

COMMENT ON COLUMN "TRADE_REPORT"."REPORTED_PERSON" IS '거래 피신고자 회원 번호';

COMMENT ON COLUMN "TRADE_REPORT"."TRADE_REPORT_CONTENT" IS '거래 신고 내용';

COMMENT ON COLUMN "TRADE_REPORT"."REFUND_FL" IS '환불 여부 환불:Y 미환불:N';

COMMENT ON COLUMN "TRADE_REPORT"."TRADE_REPORT_FILE_PATH" IS '거래 신고 첨부파일';

COMMENT ON COLUMN "TRADE_REPORT"."TRADE_NO" IS '거래 번호(FK)';
--신고 날짜 

CREATE TABLE "LIKE" (
   "SERVICE_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "LIKE"."SERVICE_NO" IS '서비스 번호(PK+FK(서비스 테이블))';

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원 번호(PK+FK)';

CREATE TABLE "GRADE" (
   "GRADE_NO"   NUMBER      NOT NULL,
   "GRADE_NAME"   VARCHAR2(20)      NOT NULL,
   "SATISFACTION"   NUMBER      NOT NULL,
   "INQUIRY_RATE"   NUMBER      NOT NULL,
   "COMPLETION_RATE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_NO" IS '등급 번호';

COMMENT ON COLUMN "GRADE"."GRADE_NAME" IS '등급 이름';

COMMENT ON COLUMN "GRADE"."SATISFACTION" IS '만족도';

COMMENT ON COLUMN "GRADE"."INQUIRY_RATE" IS '메세지 응답률';

COMMENT ON COLUMN "GRADE"."COMPLETION_RATE" IS '작업일 준수율';

CREATE TABLE "REGION" (
   "REGION_NO"   NUMBER      NOT NULL,
   "REGION_NAME"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "REGION"."REGION_NO" IS '지역 번호 SEQUENCE: SEQ_REGION_NO';

COMMENT ON COLUMN "REGION"."REGION_NAME" IS '지역 이름';

CREATE TABLE "CHAT" (
   "CHAT_NO"   NUMBER      NOT NULL,
   "CHAT_MESSAGE"   VARCHAR2(4000)      NOT NULL,
   "CHAT_SEND_TIME"   DATE   DEFAULT SYSDATE   NOT NULL,
   "CHAT_ROOM_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_NO" IS '채팅 메세지 번호 SEQUENCE: SEQ_CHAT_NO';

COMMENT ON COLUMN "CHAT"."CHAT_MESSAGE" IS '작성한 메세지';

COMMENT ON COLUMN "CHAT"."CHAT_SEND_TIME" IS '작성 시간 SYSDATE';

COMMENT ON COLUMN "CHAT"."CHAT_ROOM_NO" IS '채팅방 번호(FK)';

COMMENT ON COLUMN "CHAT"."MEMBER_NO" IS '작성자(회원번호)(FK)';

ALTER TABLE CHAT ADD READ_FL CHAR(1) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN "CHAT"."READ_FL" IS '메세지 읽음 여부 읽음:Y 안읽음:N';

CREATE TABLE "FREELANCER_ACCOUNT" (
   "FREELANCER_NO"   NUMBER      NOT NULL,
   "ACCOUNT_NO"   NUMBER      NOT NULL,
   "BANK_CODE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "FREELANCER_ACCOUNT"."FREELANCER_NO" IS '프리랜서 번호(PK+FK)';

COMMENT ON COLUMN "FREELANCER_ACCOUNT"."ACCOUNT_NO" IS '계좌 번호';

COMMENT ON COLUMN "FREELANCER_ACCOUNT"."BANK_CODE" IS '은행 코드(FK)';

CREATE TABLE "MAJOR" (
   "MAJOR_NO"   NUMBER      NOT NULL,
   "ACADEMY_NAME"   VARCHAR2(300)      NOT NULL,
   "MAJOR_NAME"   VARCHAR2(300)      NOT NULL,
   "GRADUATE_STATUS"   NUMBER      NOT NULL,
   "FREELANCER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "MAJOR"."MAJOR_NO" IS '학력 변호 SEQUENCE: SEQ_MAJOR_NO';

COMMENT ON COLUMN "MAJOR"."ACADEMY_NAME" IS '학교명';

COMMENT ON COLUMN "MAJOR"."MAJOR_NAME" IS '전공';

COMMENT ON COLUMN "MAJOR"."GRADUATE_STATUS" IS '1:재학, 2:휴학, 3:이수, 4:졸업';

COMMENT ON COLUMN "MAJOR"."FREELANCER_NO" IS '프리랜서 번호(FK)';



----------------------------------------------------------------------------------------------------
CREATE TABLE "MEMBER_REPORT" (
	"MEMBER_REPORT_NO"	NUMBER		NOT NULL,
	"MEMBER_REPORT_TITLE"	VARCHAR2(200)		NOT NULL,
	"MEMBER_REPORT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"MEMBER_REPORT_REQUEST"	VARCHAR2(4000)		NULL,
	"MEMBER_REPORT_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_MEMBER"	NUMBER		NOT NULL,
	"REPORTED_MEMBER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_REPORT"."MEMBER_REPORT_NO" IS '회원 신고 번호 SEQ_MEMBER_REPORT_NO';

COMMENT ON COLUMN "MEMBER_REPORT"."MEMBER_REPORT_TITLE" IS '회원 문의 제목';

COMMENT ON COLUMN "MEMBER_REPORT"."MEMBER_REPORT_CONTENT" IS '회원 문의 내용';

COMMENT ON COLUMN "MEMBER_REPORT"."MEMBER_REPORT_REQUEST" IS '회원 문의 답변';

COMMENT ON COLUMN "MEMBER_REPORT"."MEMBER_REPORT_CREATE_DATE" IS '회원 작성 날짜';

COMMENT ON COLUMN "MEMBER_REPORT"."REPORT_MEMBER" IS '회원 신고자(FK)';

COMMENT ON COLUMN "MEMBER_REPORT"."REPORTED_MEMBER" IS '신고 당한 회원';

CREATE TABLE "MEMBER_REPORT_FILE" (
	"MEMBER_REPORT_FILE_NO"	NUMBER		NOT NULL,
	"MEMBER_REPORT_FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"MEMBER_REPORT_FILE_ORDER"	NUMBER		NOT NULL,
	"MEMBER_REPORT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_REPORT_FILE"."MEMBER_REPORT_FILE_NO" IS '회원 신고 첨부파일 번호';

COMMENT ON COLUMN "MEMBER_REPORT_FILE"."MEMBER_REPORT_FILE_PATH" IS '회원 신고 첨부파일 경로';

COMMENT ON COLUMN "MEMBER_REPORT_FILE"."MEMBER_REPORT_FILE_ORDER" IS '회원 신고 첨부파일 순서';

COMMENT ON COLUMN "MEMBER_REPORT_FILE"."MEMBER_REPORT_NO" IS '회원 신고 번호 (FK)';
-----------------------------------------------------------------------------------
ALTER TABLE "MEMBER_REPORT" ADD CONSTRAINT "PK_MEMBER_REPORT" PRIMARY KEY (
	"MEMBER_REPORT_NO"
);

ALTER TABLE "MEMBER_REPORT_FILE" ADD CONSTRAINT "PK_MEMBER_REPORT_FILE" PRIMARY KEY (
	"MEMBER_REPORT_FILE_NO"
);

ALTER TABLE TRADE_REPORT ADD TRADE_REPORT_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL;
COMMENT ON COLUMN FMANAGER.TRADE_REPORT.TRADE_REPORT_CREATE_DATE IS '거래 신고 날짜';

ALTER TABLE "MEMBER_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_REPORT_1" FOREIGN KEY (
	"REPORT_MEMBER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_REPORT_FILE" ADD CONSTRAINT "FK_MEMBER_REPORT_TO_MEMBER_REPORT_FILE_1" FOREIGN KEY (
	"MEMBER_REPORT_NO"
)
REFERENCES "MEMBER_REPORT" (
	"MEMBER_REPORT_NO"
);
